import React from "react";
import {Inter} from "next/font/google";
import './globals.css'

export const metadata = {
    title: 'TODO App',
    description: 'Simple TODO APP Generated by Next.js',
}

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={inter.className}>
            <body className="bg-cyan-200 min-h-screen flex flex-col justify-center items-center">{children}</body>
        </html>
    )
}