import React from "react";

export const metadata = {
  title: 'TODO App',
  description: 'Simple TODO APP Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
